spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 2

#eureka
eureka:
  instance:
    #서비스 이름 대신 서비스 IP 주소 등록
    preferIpAddress: true
  client:
    #유레카 서버에 서비스 등록
    registerWithEureka: true
    #레지스트리 사본을 로컬로 가져오는설정
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:6002/eureka/

#spring boot actuator
management:
  endpints:
    web:
      exposure:
        include: "*"
#      base-path: /act
#      path-mapping:
#        health: healthcheck